/*
 * LeetCode Problem #389
 * Title: Find the Difference
 * Difficulty: Easy
 * https://leetcode.com/problems/find-the-difference/
 *
 * Description:
 * 
 * You are given two strings s and t.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Return the letter that was added to t.
 *  
 * Example 1:
 * Input: s = "abcd", t = "abcde"
 * Output: "e"
 * Explanation: 'e' is the letter that was added.
 * Example 2:
 * Input: s = "", t = "y"
 * Output: "y"
 *  
 * Constraints:
 * 	0 <= s.length <= 1000
 * 	t.length == s.length + 1
 * 	s and t consist of lowercase English letters.
 *
 * Example Test Cases:
 * "abcd"
 * "abcde"
 * ""
 * "y"
 *
 */

#include <iostream>
#include <vector>
#include <string>
#include <sstream>
#include <unordered_map>
#include <unordered_set>
#include <algorithm>
#include <queue>
#include <stack>

using namespace std;

class Solution {
public:
    char findTheDifference(string s, string t) {
        int sum = 0;

        for (int i = 0; i < s.size(); ++i) {
            sum += t[i] - s[i];
        }

        return sum + t[t.size() - 1];
    }
};

int main() {
    Solution sol;
    
    // Read input (two strings)
    string s, t;
    getline(cin, s);
    getline(cin, t);
    
    // Remove quotes if present
    if (!s.empty() && s.front() == '"' && s.back() == '"') {
        s = s.substr(1, s.length() - 2);
    }
    if (!t.empty() && t.front() == '"' && t.back() == '"') {
        t = t.substr(1, t.length() - 2);
    }
    
    // Call solution and output result
    cout << '"' << sol.findTheDifference(s, t) << '"' << endl;
    
    return 0;
}
